import numpy as np

arr = np.array([10, 20, 30, 40])
brr=np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)  
#slicing
print(arr[0]+arr[1])
print(arr[2]*arr[3]) 
print(arr[1:3])
print(arr[::2])
print(arr[::-1])
print(arr[::-2])
print(brr[:,-1])
print(brr[:-1])
print(brr[:,0:3])
print(brr[0:2, 0:2])
#arithmetic operations
print(arr+arr)
print(arr-arr)
print(arr*arr)
print(arr/arr)
print(arr**2)
print(arr*2)
print(arr+10)
#vectorised mathematics
print(np.sin(arr))
print(np.cos(arr))
print(np.tan(arr))
print(np.sqrt(arr))
print(np.log(arr))
print(np.round(arr))
radii=np.array([1, 2, 3, 4])
print(np.pi*radii**2)
array1=np.array([1, 2]) 
array2=np.array([3, 4])
print(array1+array2)
print(array1-array2)
print(array1*array2)
print(array1/array2)